### Register a User
POST http://localhost:4000/register
Content-Type: application/json

{
    "name": "Srinu",
    "address": "15-300, Kerela"
}

###

//GET all Users
GET http://localhost:4000/users

###

//GET all Addresses
GET http://localhost:4000/address

###
